db:
  driver: "com.mysql.cj.jdbc.MysqlDataSource"
  url: "jdbc:h2:mem:test;MODE=MYSQL;DB_CLOSE_DELAY=-1"
  user: "sa"
  password: ""

service:
  enable: true
  enableHttp2: true
  enableWebsockets: false
  secure: true
  host: localhost
  port: 30315
  apis:
    - account
    - admin
    - block
    - contract
    - personal
    - transaction
