sudo: false
language: scala

scala:
  - 2.12.6

jdk:
  - openjdk11

before_install:
  - export PATH=${PATH}:./vendor/bundle

install:
  - rvm use 2.3.0 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1

script:
  - sbt ++$TRAVIS_SCALA_VERSION ci
  - sbt ++$TRAVIS_SCALA_VERSION docs/makeMicrosite

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $TRAVIS_REPO_SLUG == "c-block/jbok" && test $TRAVIS_SCALA_VERSION == "2.12.4" && sbt docs/publishMicrosite
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.coursier
    - $HOME/.sbt

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.coursier/cache -name "*.lock" -type f -delete
