name: IotChain
baseurl: /iotchain
description: IotChain, to be a type-safe, functional and flexible blockchain
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.1-SNAPSHOT
org: org.iotchain
markdown: kramdown
