version: '3.3'

services:
  prometheus:
    image: prom/prometheus:v2.8.1
    volumes:
      - ./etc/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  node-exporter:
    image: prom/node-exporter:v0.17.0
    ports:
      - 9100:9100

  grafana:
    image: grafana/grafana:6.1.0
    volumes:
      - ./etc/grafana:/etc/grafana
    environment:
      GF_INSTALL_PLUGINS: 'grafana-piechart-panel'
    depends_on:
      - prometheus
    ports:
      - 3000:3000

  iotchain:
    image: iotchain/iotchain:<version>
    restart: always
    volumes:
      - ./etc/iotchain:/etc/iotchain:ro
      - ./var/lib/iotchain:/var/lib/iotchain
      - ./var/log/iotchain:/var/log/iotchain
    ports:
      - 30314:30314
      - 30315:30315
