rootPath: /var/lib/iotchain
genesis:
  chainId: '10'
  alloc:
    '0x9ae26e686DDB7A1e702422E3713B4b8C4DDB0338': '700000000000000000000000000'
    '0xeE2a526Ef8D2bc09A0A6f1201C0A691349CE4c41': '300000000000000000000000000'
  miners:
    - '0xfba6ebcb8a45cec3019e1dcd39ad74353b64935a'
    - '0x076dd078fbdd4b7cfec501cc2623448bd29a79d7'
    - '0xeca4d3e1c636b207ba2c65024e6244a7c9e6fd0e'
  timestamp: 1565171034000
  coinbase: '0x0000000000000000000000000000000000000000'
  difficulty: '0'
  gasLimit: '16716680'
log:
  logDir: /var/log/iotchain/logs
  level: INFO
  maxLogs: 15
history:
    frontierBlockNumber: '0'
    homesteadBlockNumber: '0'
    tangerineWhistleBlockNumber: '0'
    spuriousDragonBlockNumber: '0'
    byzantiumBlockNumber: '0'
    constantinopleBlockNumber: '1000000000000000000000'
keystore:
  initkey: ''
  dir: /etc/iotchain/keystore
peer:
  host: 0.0.0.0
  port: 30314
  seeds:
    - tcp://47.102.121.72:30314
    - tcp://139.196.160.72:30314
    - tcp://139.196.160.93:30314
  updatePeersInterval: 10 seconds
  maxOutgoingPeers: 1000
  maxIncomingPeers: 1000
  minPeers: 1
  bufferSize: 4194304
  timeout: 10 seconds
sync:
  maxBlockHeadersPerRequest: 128
  maxBlockBodiesPerRequest: 128
  offset: 10
  checkInterval: 5 seconds
  banDuration: 200 seconds
  requestTimeout: 10 seconds
txPool:
  poolSize: 4096
  transactionTimeout: 10 minutes
blockPool:
  maxBlockAhead: 10
  maxBlockBehind: 10
mining:
  enabled: false
  address: '0x0000000000000000000000000000000000000000'
  passphrase: changeit
  coinbase: '0x0000000000000000000000000000000000000000'
  period: 5000 milliseconds
  epoch: 30000
  minBroadcastPeers: 4
persist:
  driver: rocksdb
  path: /var/lib/iotchain/data
  columnFamilies:
    - default
    - BlockHeader
    - BlockBody
    - Receipts
    - Snapshot
    - Node
    - Code
    - TotalDifficulty
    - AppState
    - Peer
    - NumberHash
    - TxLocation
ssl:
  enabled: false
  keyStorePath: /etc/iotchain/cert/server.jks
  trustStorePath: /etc/iotchain/cert/cacert.jks
  protocol: TLS
  clientAuth: NotRequested
db:
  driver: org.sqlite.JDBC
  url: jdbc:sqlite:/var/lib/iotchain/service.db
  user: root
  password: password
service:
  enable: true
  enableHttp2: true
  enableWebsockets: false
  secure: false
  logHeaders: true
  logBody: false
  enableMetrics: true
  allowedOrigins: []
  local: 0.0.0.0
  host: <your host external ip>
  port: 30315
  apis:
    - account
    - block
    - contract
    - transaction
