rootPath: /var/lib/iotchain
genesis:
  chainId: '10'
  alloc:
    '0x42405c55b353ff24e09b02374a0d8abdbf11d052': '1000000000000000000000000000000'
    '0xa490d92a1945744acb9700e5c3df74d7ffffd1ba': '1000000000000000000000000000000'
  miners:
    - '0xa490d92a1945744acb9700e5c3df74d7ffffd1ba'
  timestamp: 1558964460504
  coinbase: '0x0000000000000000000000000000000000000000'
  difficulty: '0'
  gasLimit: '16716680'
log:
  logDir: /var/log/iotchain
  level: INFO
  maxLogs: 15
history:
    frontierBlockNumber: '0'
    homesteadBlockNumber: '0'
    tangerineWhistleBlockNumber: '0'
    spuriousDragonBlockNumber: '0'
    byzantiumBlockNumber: '0'
    constantinopleBlockNumber: '1000000000000000000000'
keystore:
  initkey: ''
  dir: /etc/iotchain/keystore
peer:
  host: 0.0.0.0
  port: 30314
  seeds:
    - tcp://127.0.0.3:30314
    - tcp://127.0.0.4:30314
  updatePeersInterval: 10 seconds
  maxOutgoingPeers: 10
  maxIncomingPeers: 10
  minPeers: 1
  bufferSize: 4194304
  timeout: 10 seconds
sync:
  maxBlockHeadersPerRequest: 128
  maxBlockBodiesPerRequest: 128
  offset: 10
  checkInterval: 5 seconds
  banDuration: 200 seconds
  requestTimeout: 10 seconds
txPool:
  poolSize: 4096
  transactionTimeout: 10 minutes
blockPool:
  maxBlockAhead: 10
  maxBlockBehind: 10
mining:
  enabled: true
  address: '0xa490d92a1945744acb9700e5c3df74d7ffffd1ba'
  passphrase: changeit
  coinbase: '0xc0e5f5502f906c55382090448b4a122fdf7db192'
  period: 5000 milliseconds
  epoch: 30000
  minBroadcastPeers: 4
persist:
  driver: rocksdb
  path: /var/lib/iotchain/data
  columnFamilies:
    - default
    - BlockHeader
    - BlockBody
    - Receipts
    - Snapshot
    - Node
    - Code
    - TotalDifficulty
    - AppState
    - Peer
    - NumberHash
    - TxLocation
ssl:
  enabled: false
  keyStorePath: /etc/iotchain/cert/server.jks
  trustStorePath: /etc/iotchain/cert/cacert.jks
  protocol: TLS
  clientAuth: NotRequested
db:
  driver: org.sqlite.JDBC
  url: jdbc:sqlite:/var/lib/iotchain/service.db
  user: root
  password: password
service:
  enable: true
  enableHttp2: true
  enableWebsockets: false
  secure: false
  logHeaders: true
  logBody: false
  enableMetrics: true
  allowedOrigins: []
  local: 0.0.0.0
  host: 127.0.0.2
  port: 30315
  apis:
    - account
    - admin
    - block
    - contract
    - miner
    - personal
    - transaction
